blog/urls.py
from django.urls import path, include
from .import views 
from django.conf.urls import url

app_name = "blog"


urlpatterns = [
    path('add/', views.add_blog, name='add_blog'),
    path('', views.show, name="show"),
    path('<slug:slug>/', views.view_post, name='post_detail'),
    #path('sana/', views.ps, name="PostList")
    
]

pioneer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include 
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from accounts import views as user_views

# #from . import views as core_views
# #from django.views.generic.base import TemplateView

# #from rest_framework.authtoken import views
#from blog.views import *
# from accounts.views import *



urlpatterns = [
   path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
   path('accounts/', include('accounts.urls')),
   path('blog/', include('blog.urls', namespace='blog')),
   path ('courses/', include('courses.urls')),
   path('', views.index, name='index'),
   path('special/',views.special, name='special'),
   path('logout/', views.user_logout, name='logout'),
    
   path('accounts/login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'), #login url

   path('accounts/password-reset/', auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html'),
            name='password_reset'),
    
   path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
         ), name='password_reset_done'),
    
   path('accounts/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html'
         ), name='password_reset_confirm'),
    
   path('accounts/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
         ), name='password_reset_complete'),
    
    

]
if settings.DEBUG: 

        urlpatterns += static(settings.MEDIA_URL, 

                              document_root=settings.MEDIA_ROOT) 
 

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=250, unique=True,)
    author = models.ForeignKey(User, on_delete= models.CASCADE)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, default='', null=False)
    email = models.EmailField(max_length=75, default='', null=False)
    content= models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    #author = models.ForeignKey(User, default="", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.content
    

blog/forms.py
from django import forms
from blog.models import Post, Comment
from django.contrib.auth.models import User
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter title.'}), required=True, max_length=200)
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Enter content.'}), required=True,)
    status = forms.ChoiceField(choices=STATUS, widget=forms.Select(), required=True)
    
    class Meta():
        model=Post
        exclude =['author', 'slug']

class CommentForm(forms.ModelForm):
    
    #title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter title.'}), required=True, max_length=200)
    #content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Enter content.'}), required=True, max_length=200)
    #status = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter status.'}), required=True,)
    
    class Meta():
        model= Comment
        exclude=['post']

blog/views.py
from django.views import generic
from django.shortcuts import render,redirect, HttpResponse, get_object_or_404
from .models import *
from django.contrib.auth.models import User
from .forms import *
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#@user_passes_test(lambda u: u.is_superuser)
@login_required
def add_blog(request):
    
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            status=form.cleaned_data.get('status')
            post=form.save(commit=False)
            post.author= request.user
            post.save()
            return redirect("/blog")
    else:
        form=PostForm()
    return render(request, 'blog/blog_post.html', {'form':form})
           

def view_post(request, slug):
    post=get_object_or_404(Post, slug=slug)
    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect(request.path)
    else:
        form=CommentForm()
    
    form.initial['name'] = request.session.get('name')
    form.initial['email'] = request.session.get('email')
    arg={'form':form, "post":post}
    return render(request, "blog/post_detail.html", arg)

def show(request):
    post1= Post.objects.filter(status=1).order_by('-created_on')
    page = request.GET.get('page', 1)

    paginator = Paginator(post1, 5)
    try:
        post2 = paginator.page(page)
    except PageNotAnInteger:
        post2 = paginator.page(1)
    except EmptyPage:
        post2 = paginator.page(paginator.num_pages)
    return render(request, "blog/index.html", {'post1':post1, 'post2':post2})

blog/templates/blog/blog_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block head %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>
{% endblock %}
{% block body %}
<div style="background-color:#f39c1;">

    <br><br>
    <div class="container navy-blue-skin">
        <div class="row mx-auto">
            <div class="col-lg-7 col-md-10  ">
                <div class="card w-100 peach-gradient">
                    <div class="card-body ">
                        <h1 class="text-center"> Add Blog Here!
                            <hr>
                        </h1>
                        <form method='post'>
                            {% csrf_token %}
                            {{ form|crispy }}

                            <input type="submit" class="btn aqua-gradient w-100" value="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %} 
{% block body %}
<style>
     .col1 {padding-right:25%;}
    @media only screen and (max-width: 768px) {
        .col1{
        padding-right: 8%;
  }
  </style>
<div>
    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <br><br>
                        <h1 class=" site-heading text-light  ">
                            Welcome to my awesome Blog 
                            <hr>
                        </h1>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 ">
                {% for post in post2 %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}}
                        <hr>
                        </p>
                        <p class="card-text">{{post.content|slice:":200" }}</p>
                        <a href="  {{post.slug}}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
</div>
<br>
<!--======================================PAGINATION===========================================================-->
    <div class=" container b col1">
        <div class=" card peach-gradient ">
            {% if post2.has_other_pages %}
            <ul class="pagination">
                {% if post2.has_previous %}
                <li><a href="?page={{ post2.previous_page_number }}">&laquo;&nbsp;</a></li>
                {% else %}
                <li class="disabled"><span>&laquo;&nbsp;</span></li>
                {% endif %}
                {% for i in post2.paginator.page_range %}
                {% if post2.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}&nbsp;</a></li>
                {% endif %}
                {% endfor %}
                {% if post2.has_next %}
                <li><a href="?page={{ post2.next_page_number }}">&raquo;&nbsp;</a></li>
                {% else %}
                <li class="disabled"><span>&raquo;&nbsp;</span></li>
                {% endif %}
            </ul>
            {% endif %}
</div>
</div><br><br><br><br>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% block body %}
{% load crispy_forms_tags %}
{% load static %}
<style>
  .text{
    color:cyan;
  }
</style>
<br><br>
<div class="container w-90">

  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <h1 class="text-center purple-gradient">Blog Detail</h1><hr>

      <div class="card-body">
        <h1>{{ post.title }}</h1><hr>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      <h6 class="peach-gradient ">.</h6>
      </div>
    </div>
        {% comment %} {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %} {% endcomment %}

  </div>
    
    {% if post.comment_set.all %}
      <h1 class="text-dark  ">  Comments! <hr></h1>
    
      <div class="row">
        <div class="col-md-8 card mb-4 mt-3 left">
          <div class="card-body">
          {% for comment in post.comment_set.all %}
            <h6 class="aqua-gradient">.</h6>
            <h3 >{{comment.name}}<small class=" text-muted "> &nbsp;reply</small></h3>
            <p class=" text-muted">{{ comment.created_on }}</p>
            <p class="card-text ">{{ comment.content | safe }}</p>
            {% comment %} <h6 class="bg-success">.</h6> {% endcomment %}

          {% endfor %}
          </div>
        </div>
      </div>
    
    {% endif %}
    


<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Write comment to us</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <form method="post" autocomplete="on">
          {% csrf_token %}
          <div class="modal-body mx-3">
            <div class="md-form mb-5">
              <i class="fas fa-user prefix grey-text"></i>
              <input type="text" name="name" maxlength="50" class=" form-control validate" id="form34" required id="id_name" onclick="myFunction(document.getElementById('your-name'))">
              <label id="your-name" data-error="wrong" data-success="right" for="form34" >Your name</label>
            </div>

            <div class="md-form mb-5">
              <i class="fas fa-envelope prefix grey-text"></i>
              <input type="email" name="email" maxlength="75" class="form-control validate" id="form29" required id="id_email" onclick="myFunction(document.getElementById('your-email'))">
              <label id="your-email" data-error="wrong" data-success="right" for="form29">Your email</label>
            </div>


            <div class="md-form">
              <i class="fa fa-tag prefix grey-text"></i>
               <textarea name="content" cols="40" rows="10" class="md-textarea form-control" required id="id_content" onclick="myFunction(document.getElementById('your-content'))"></textarea>
              <label id="your-content" data-error="wrong" data-success="right" for="form8">Your message</label>
            </div>

          </div>
          <div class="modal-footer d-flex justify-content-center">
            <button type="submit" name="button" class="btn btn-unique">Send <i class="fas fa-paper-plane-o ml-1"></i></button>
          </div>
      </form>

    </div>
  </div>
</div>

<div>
  <a href="" class="btn btn-default w-50 btn-rounded mb-4" data-toggle="modal" data-target="#modalContactForm"><b>Write Comment<b></a>
</div>
<script>
function myFunction(element) {
  //element is label here 
  element.classList.add("active");
}
</script>


{% endblock  %}